<div class="customer_current_service_requests">
    <p>Current Service Requests</p>
    <button class="add_new_service_request_btn" onclick="window.location.href='<?=url('/book-now')?>' ">Add New Service Request</button>
</div>

<table id="current_service_requests_table">
    <thead>
        <tr>
            <th>Service Id</th>
            <th>Service Date</th>
            <th>Service Provider</th>
            <th>Payment</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <!-- DYNAMIC GENERATED BY DATATABLE -->
    </tbody>
</table>

<script>

    $(document).ready(()=>{

        state.customer_dashboard_table = $('#current_service_requests_table').DataTable({
            searching : false,
            serviceSide : true,
            dom : 't<"datatable_bottom"lp>',
            ajax : {
                url : `${BASE_URL}/customer-current-services`,
                cache : true,
                dataSrc : function(data){
                    // STORE DATA GLOBALLY...
                    state.customer_dashboard_data = data;
                    return data;
                },
            },
            columns :[
                {
                    mRender : function(data, type, row){
                        return`<p class="service_id" onclick="show_service_details(${row.ServiceRequestId});">${row.ServiceRequestId}</p>`;
                    },
                },
                {
                    mRender : function(data, type, row){
                        return` <div class="service_date" onclick="show_service_details(${row.ServiceRequestId});">
                                    <div>
                                        <img src="<?= assets('assets/img/table/calendar.png'); ?>" alt="">
                                        <p>${row.ServiceDate}</p>
                                    </div>
                                    <div>
                                        <img src="<?= assets('assets/img/table/time.png'); ?>" alt="">
                                        <p><span>${row.StartTime}</span> - <span>${row.EndTime}</span></p>
                                    </div>
                                </div>`;
                    }
                },
                {
                    mRender : function(data, type, row){
                            return 'No SP';
                            // return `<div class="service_provider">
                            //             <img class="hat_style" src="<?= assets('assets/img/table/hat.png'); ?>" alt="">
                            //             <div>
                            //                 <p>Lyum Watson</p>    
                            //                 <div>
                            //                     <i class="fas fa-star rated_star"></i>
                            //                     <i class="fas fa-star rated_star"></i>
                            //                     <i class="fas fa-star rated_star"></i>
                            //                     <i class="fas fa-star rated_star"></i>
                            //                     <i class="fas fa-star unrated_star"></i>
                            //                     <span>4</span>
                            //                 </div>
                            //             </div>
                            //         </div>`;
                    }
                },
                {
                    mRender : function(data, type, row){
                    // €₹
                    return `<p class="payment_text" onclick="show_service_details(${row.ServiceRequestId});"><span>${row.TotalCost}</span> ₹</p>`;
                    }
                },
                {
                    mRender : function(data, type, row){
                        return `<div class="table_btn_container">
                                    <button class="reschedule_btn" onclick='reschedule_service(${row.ServiceRequestId});'>Reschedule</button>
                                    <button class="cancel_btn" onclick='cancel_service(${row.ServiceRequestId});'>Cancel</button>    
                                </div>`;
                    }
                }
            ],
            pagingType : 'full_numbers',
            language : {
                paginate : {
                    first    :'<i class="fa-solid fa-backward-step"></i>',
                    previous :'<i class="fas fa-angle-left">',  
                    next     :'<i class="fas fa-angle-right">',
                    last     :'<i class="fa-solid fa-forward-step"></i>'  
                },
            }
        });
    });
</script>

<script>

    // SHOW SERVICE DETAILS...
    function show_service_details(id){
        let data = state.customer_dashboard_data.filter((service)=>{
            if(id===service.ServiceRequestId){
                return service;
            }
        });
        data = data[0];
        // EXTRA SERVICES BAKI 6E...
        // SETUP HTML... $ ₹
        let html = `
        <p class="popup_title">Service Details</p>
        <div>
            <p>${data.ServiceDate} | ${data.StartTime} - ${data.EndTime}</p>
            <p>Duration : <span>${data.Duration} Hours</span></p>
        </div>
        <div>
            <p>Service Id : <span>${data.ServiceRequestId}</span></p>
            <p>Extras : <span>Inside Cabinats</span></p>
            <p>Net Amout : <span class="price_text">${data.TotalCost} ₹</span></p>
        </div>
        <div>
            <p>Service Address : <span>${data.AddressLine1} ${data.AddressLine2}, ${data.PostalCode} ${data.City} </span></p>			
            <p>Billing Address : <span>Same as Cleaning Address</span></p>
            <p>Phone : <span>+49 ${data.Mobile}</span></p>
            <p>Email : <span>${data.Email}</span></p>
        </div>
        <div>
            <p>Conmments : <span>${data.Comments}</span></p>
        </div>
        <div class="table_btn_container">
            <button class="reschedule_btn" onclick="reschedule_service(${data.ServiceRequestId});"><i class="fas fa-redo-alt"></i> Reschdule</button>
            <button class="cancel_btn" onclick="cancel_service(${data.ServiceRequestId});"><i class="fas fa-times"></i> Cancel</button>
        </div>`;

        // ASSIGN DYNAMIC HTML BEFORE OPEN MODEL...
        $('#service_details_popup').html(html);
        open_model('service_details');

    }

    // CANCEL SERVICE REQUEST...
    function reschedule_service(id){
        state.reschedule_service_id = id;
        open_model('reschedule_service_request');
    }

    // CANCEL SERVICE REQUEST...
    function cancel_service(id){
        state.cancel_service_id = id;
        open_model('cancel_service_request');
    }

</script>