<div class="customer_service_history">
    <p>Service History</p>
    <button class="export_btn">Export</button>
</div>
<table id="customer_service_history_table">
    <thead>
        <tr>
            <th>Service Details</th>
            <th>Service Provider</th>
            <th>Payment</th>
            <th>Status</th>
            <th>Rate SP</th>    
        </tr>
    </thead>
    <tbody>
        <!-- TABLE DATA DYNAMICALLY GENERATED BY DATATABLE -->
    </tbody>
</table><!-- END_SERVICE_HISTORY_TABLE -->


<script>

    $(document).ready(function(){
        state.customer_service_history_table = $('#customer_service_history_table').DataTable({
            searching : false,
            serviceSide : true,
            autoWidth : false,
            dom : 't<"datatable_bottom"lp>',
            ajax : {
                url : `${BASE_URL}/customer-all-services`,
                cache : true,
                dataSrc : function(data){
                    // STORE DATA GLOBALLY...
                    state.customer_service_history_data = data;
                    return data;
                },
            },
            columns :[
                {
                    mRender : function(data, type, row){
                        return`<div class="service_details" onclick="show_service_details(${row.ServiceRequestId});">
                                    <div>
                                        <img src="<?= assets('assets/img/table/calendar_black.png'); ?>" alt="">
                                        <p>${row.ServiceDate}</p>
                                    </div>
                                    <div>
                                        <p>${row.StartTime} - ${row.EndTime}</p>
                                    </div>
                                </div>`;
                    },
                },
                {
                    mRender : function(data, type, row){
                        if(row.ServiceProvider!==undefined){
                            if(row.Rating!==undefined){
                                return `<div class="service_provider">
                                        <img class="hat_style" src="${BASE_URL}/${row.ServiceProvider.UserProfilePicture}" alt="">
                                        <div>
                                            <p>${row.ServiceProvider.FirstName} ${row.ServiceProvider.LastName}</p>    
                                            <div>
                                                <i class="fas fa-star rated_star"></i>
                                                <i class="fas fa-star rated_star"></i>
                                                <i class="fas fa-star rated_star"></i>
                                                <i class="fas fa-star rated_star"></i>
                                                <i class="fas fa-star unrated_star"></i>
                                                <span>${row.Rating}</span>
                                            </div>
                                        </div>
                                    </div>`;
                            }
                            else{
                                return `<div class="service_provider">
                                        <img class="hat_style" src="${BASE_URL}/${row.ServiceProvider.UserProfilePicture}" alt="">
                                        <div>
                                            <p>${row.ServiceProvider.FirstName} ${row.ServiceProvider.LastName}</p>    
                                            <div>
                                                <i class="fas fa-star unrated_star"></i>
                                                <i class="fas fa-star unrated_star"></i>
                                                <i class="fas fa-star unrated_star"></i>
                                                <i class="fas fa-star unrated_star"></i>
                                                <i class="fas fa-star unrated_star"></i>
                                                <span></span>
                                            </div>
                                        </div>
                                    </div>`;
                            }
                        }
                        else{
                            return 'No SP';
                        }
                    }
                },
                {
                    mRender : function(data, type, row){
                        // €
                        return `<p class="payment_text">₹<span>${row.TotalCost}</span></p>`;
                    }
                },
                {
                    mRender : function(data, type, row){
                        switch(row.Status){
                            case 0:
                                return `<p class="new_status">New</p>`;
                            case 1:
                                return `<p class="pending_status">Pending</p>`;
                            case 2:
                                return `<p class="completed_status">Completed</p>`;
                            case 3:
                                return `<p class="cancelled_status">Cancelled</p>`;
                        }
                    }
                },
                {
                    mRender : function(data, type, row){
                        // NULL : NEW
                        // 1    : PENDING
                        // 2    : COMPLETED
                        // 3    : CANCALLED
                        if(row.Status==2){
                            return `<button class="rate_sp_btn" onclick="rateSP(${row.ServiceRequestId});">Rate SP</button>`;
                        }
                        else{
                            return `<button class="rate_sp_btn" disabled>Rate SP</button>`;
                        }
                    }
                }
            ],
            pagingType : 'full_numbers',
            language : {
                paginate : {
                    first    :'<i class="fa-solid fa-backward-step"></i>',
                    previous :'<i class="fas fa-angle-left">',  
                    next     :'<i class="fas fa-angle-right">',
                    last     :'<i class="fa-solid fa-forward-step"></i>'  
                },
            }
        });
    });
</script>

<script>

    function rateSP(id){
        state.rate_service_id = id;

        let data = state.customer_service_history_data;

        data = data.filter((service)=>{
            if(service.ServiceRequestId==id){
                return service;
            }
        });

        data = data[0];

        // ASSIGN HTML BEFORE OPEN MODEL
        $('#rating_popup').html(`
            <div class="service_provider">
                <img class="hat_style" src="${BASE_URL}/${data.ServiceProvider.UserProfilePicture}" alt="">
                <div>
                    <p>${data.ServiceProvider.FirstName} ${data.ServiceProvider.LastName}</p>    
                    <div>
                        <i class="fas fa-star unrated_star"></i>
                        <i class="fas fa-star unrated_star"></i>
                        <i class="fas fa-star unrated_star"></i>
                        <i class="fas fa-star unrated_star"></i>
                        <i class="fas fa-star unrated_star"></i>
                        <span></span>
                    </div>
                </div>
            </div>
            <!-- NEED TO TEXT ALIGN LEFT -->
            <p class="popup_title" style="text-align: left;">Rate your Service Provider</p>
            <div class="rate_type">
                <div>
                    <p>On time arrival</p>    
                    <i class="fas fa-star rated_star"></i>
                    <i class="fas fa-star rated_star"></i>
                    <i class="fas fa-star unrated_star"></i>
                    <i class="fas fa-star unrated_star"></i>
                    <i class="fas fa-star unrated_star"></i>
                </div>
                <div>
                    <p>Friendly</p>    
                    <i class="fas fa-star rated_star"></i>
                    <i class="fas fa-star rated_star"></i>
                    <i class="fas fa-star rated_star"></i>
                    <i class="fas fa-star unrated_star"></i>
                    <i class="fas fa-star unrated_star"></i>
                </div>
                <div>
                    <p>Quality of Service</p>
                    <i class="fas fa-star rated_star"></i>
                    <i class="fas fa-star rated_star"></i>
                    <i class="fas fa-star rated_star"></i>
                    <i class="fas fa-star rated_star"></i>
                    <i class="fas fa-star unrated_star"></i>
                </div>
            </div><!-- RATE TYPE -->
            <div>
                <div class="form_group">
                    <label class="label" for="">Feedback on service provider</label>
                    <textarea class="textarea" name="rating_feedback"></textarea>
                    <div class="validation_message d_none">
                        <p>Enter Feedback</p>
                    </div>
                </div>
                <button class="popup_btn">Submit</button>
            </div>
        `);
        open_model('rating');
    }

</script>