<div class="block_customer">
    <!-- CARD GENERATED BY JAVASCRIPT -->
</div>

<!-- **********SP-BLOCK-CUSTOMER********** -->
<script>
    $.ajax({
        url : `${BASE_URL}/sp-my-customer`,
        method : 'GET',
        success : function(res){
            if(res!=="" && res!==undefined){
                try{
                    const result = JSON.parse(res);
                    state.sp_my_customer = result;
                    let html = ``;
                    for(let i=0; i<result.length; i++){
                        html += `<div class="block_customer_card">
                                    <div>
                                        <img src="<?= assets('assets/img/table/hat.png'); ?>" alt="">
                                    </div>
                                    <p>${result[i].FirstName} ${result[i].LastName}</p>
                                    <button class="block_btn" onclick="block_customer(${result[i].UserId})">Block</button>
                                </div>`;
                    }
                    $('.block_customer').html(html);
                }
                catch(e){
                    console.log('Invalid JSON Response!');
                }
            }
        },
        error : function(obj){
            if(obj!==undefined){
                const {responseText} = obj;
                const error = JSON.parse(responseText);
                console.log(error.message);
            }
        }
    });
</script>