<div class="sp_new_service_request" style="padding-bottom:10px;">
    <!-- <div>
        <p>Service Area</p>
        <select name="" id="">
            <option value="">25</option>
        </select>
    </div> -->
    <div>
        <input type="checkbox">
        <label for="">including pet at home</label>
    </div>    
</div>
<table id="sp_new_services_table">
    <thead>
        <tr>
            <th>Service Id</th>
            <th>Service Date</th>
            <th>Customer Details</th>
            <th>Payment</th>
            <th>Time Conflict</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        <!-- DYNAMICALY GENERATED BY DATATABLE... -->
    </tbody>
</table>

<!-- **********NEW-SERVICE-REQUEST********** -->
<script>
    $(document).ready(function(){
        state.sp_new_services_table = $('#sp_new_services_table').DataTable({
            searching : false,
            serviceSide : true,
            autoWidth : false,
            dom : 't<"datatable_bottom"lp>',
            ajax : {
                url : `${BASE_URL}/sp-new-services`,
                cache : true,
                dataSrc : function(data){
                    // STORE DATA GLOBALLY...
                    state.sp_new_services_data = data;
                    return data;
                },
            },
            columns :[
                {
                    mRender : function(data, type, row){
                        return`<p class="service_id">${row.ServiceRequestId}</p>`;
                    },
                },
                {
                    mRender : function(data, type, row){
                        return `<div class="service_date">
                                    <div>
                                        <img src="<?= assets('assets/img/table/calendar.png'); ?>" alt="">
                                        <p>${row.ServiceDate}</p>
                                    </div>
                                    <div>
                                        <img src="<?= assets('assets/img/table/time.png'); ?>" alt="">
                                        <p>${row.StartTime} to ${row.EndTime}</p>
                                    </div>
                                </div>`;
                    }
                },
                {
                    mRender : function(data, type, row){
                        return `<div class="customer_details"> 
                                    <p>${row.CustomerName}</p>
                                    <div>
                                        <img src="<?= assets('assets/img/table/home.png'); ?>" alt="">
                                        <p>${row.AddressLine1} ${row.AddressLine2}, ${row.PostalCode} ${row.City}</p>
                                    </div>
                                </div>`;
                    }
                },
                {
                    mRender : function(data, type, row){
                        // €
                        return `<p class="payment_text">₹<span>${row.TotalCost}</span></p>`;
                    }
                },
                {
                    mRender : function(data, type, row){
                        return ``;
                    }
                },
                {
                    mRender : function(data, type, row){
                        return `<div>
                                    <button class="accept_btn" onclick="accept_service(${row.ServiceRequestId});">Accept</button>
                                </div>`;
                    }
                }
            ],
            pagingType : 'full_numbers',
            language : {
                paginate : {
                    first    :'<i class="fa-solid fa-backward-step"></i>',
                    previous :'<i class="fas fa-angle-left">',  
                    next     :'<i class="fas fa-angle-right">',
                    last     :'<i class="fa-solid fa-forward-step"></i>'  
                },
            }
        });
    });
</script>
