<div class="user_management">
    <div>
        <p>User Management</p>
        <button class="add_new_user_btn"><i class="fas fa-plus"></i> Add New User</button>
    </div>
    <div>
        <select class="select" name="" id="">
            <option value="">User Name</option>
        </select>
        <select class="select" name="" id="">
            <option value="">User Role</option>
        </select>
        <div class="phone_number">
            <label for="">+46</label>
            <input type="text" placeholder="Phone Number">
        </div>
        <input class="input" type="text" placeholder="Zip Code" id="searchByZipCode">
        <button class="search_btn">Search</button>
        <button class="clear_btn">Clear</button>
    </div>
</div><!-- END_USER_MANAGEMENT -->

<table id="admin_user_management_table">
    <thead>
        <tr>
            <th>User Name</th>
            <!-- <th>User Type</th> -->
            <th>Date of Registration</th>
            <th>Role</th>
            <th>Phone</th>
            <th>Postal Code</th>
            <!-- <th>City</th>
            <th>Radius</th> -->
            <th>Status</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <!-- DYNAMIC GENERATED BY DATATABLE -->
    </tbody>
</table><!-- END_USER_MANAGEMENT_TABLE -->

<!-- **********ADMIN-USER-MANAGEMENT********** -->
<script>
    $(document).ready(function(){
        state.admin_user_management_table = $('#admin_user_management_table').DataTable({
            searching : false,
            serviceSide : true,
            autoWidth : false,
            filter : true,
            dom : 't<"datatable_bottom"lp>',
            ajax : {
                url : `${BASE_URL}/user-management`,
                cache : true,
                dataSrc : function(data){
                    // STORE DATA GLOBALLY...
                    data = data.filter((i)=>{
                        if(i.RoleId!==3){
                            return i;
                        }
                    })                    
                    state.admin_user_management_data = data;
                    // CUSTOM FILTER DATA...
                    return data;
                }
            },
            columns : [
                {
                    render : function(data, type, row){
                        return `${row.FirstName} ${row.LastName}`;
                    }
                },
                {
                    render : function(data, type, row){
                        return `${row.CreatedDate}`;
                    }
                },
                {
                    render : function(data, type, row){
                        switch(row.RoleId){
                            case 1:
                                return `Customer`;
                            case 2:
                                return `Service Provider`;
                            default:
                                return ``;
                        }
                    }
                },
                {
                    render : function(data, type, row){
                        return `${row.Mobile}`;
                    }
                },
                {
                    render : function(data, type, row){
                        if(row.ZipCode!=null)
                            return `${row.ZipCode}`;
                        else
                            return ``;
                    }
                },
                {
                    render : function(data, type, row){
                        switch(row.IsActive){
                            case 0:
                                return `<p class="inactive_status">Inactive</p>`;
                            case 1:
                                return `<p class="active_status">Active</p>`;
                            default:
                                return `<p class="inactive_status">InActive</p>`;
                        } 
                    }
                },
                {
                    render : function(data, type, row){
                        return `<div class="dropdown">
                                    <button class="dropdown_btn"><i class="fas fa-ellipsis-v"></i></button>
                                    <div class="dropdown_menu d_none">
                                        <a href="">Active</a>
                                        <a href="">Disactive</a>
                                        <a href="">Service History</a>
                                    </div>
                                </div>`;                    
                    }
                },
            ],
            pagingType : 'full_numbers',
            language : {
                paginate : {
                    first    :'<i class="fa-solid fa-backward-step"></i>',
                    previous :'<i class="fas fa-angle-left">',  
                    next     :'<i class="fas fa-angle-right">',
                    last     :'<i class="fa-solid fa-forward-step"></i>'  
                },
            }
        })

        $('#searchByZipCode').keyup(()=>{
            console.log('a');
            const searchVal = $('#searchByZipCode').val();
            state.admin_user_management_table.column(5).search(searchVal).draw();
        });

    });
</script>


